30/03/2022 00:26:44.955 | ERROR | main.py | <module> | Exception: Improper token has been passed.

